<?php

namespace Tests\Feature;

use App\Inspections\Spam;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SpamTest extends TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withExceptionHandling();
    }

    public function test_it_validates_for_invalid_key_words()
    {

        //invalid KeyWords

        // key Held down
        $spam = new Spam();
        $this->assertFalse($spam->detect('Innocent reply Here'));
        
    }

    public function test_it_checks_for_any_key_been_held_down()
    {
        // key Held down

        $spam = new Spam();
        $this->expectException('Exception');
        $spam->detect('Hello World aaaaaaaaa');
    }
}
